### ISSUE TITLE
Favicon is not displayed on the landing page

### ISSUE THREAD

**Issue by tim-krieger** [kitsteam/mindwendel#10]

**Comment by JannikStreek** [comment]
can you try removing the cache of your browser and then opening the website again? I think its a caching problem, the favicon is displayed everywhere for me - but it was a "blank" image before which might have been cached.

**Comment by tim-krieger** [comment]
The browser console shows me the following:

`Failed to load resource: the server responded with a status of 404 () favicon...ico`

Maybe something ist configured wrong on our side. I can reproduce it with Chromium and Firefox.

**Comment by tim-krieger** [comment]
And the html code of the landing page contains this line:

<link rel="icon" type="image/x-icon" href="/favicon-ce0263eb2608931ef7710d2d40264aa7.ico?vsn=d">

Maybe you would like to test our implementation https://idea.kits.blog?

**Comment by tim-krieger** [comment]
I think you could find a solution [here](https://github.com/phoenixframework/phoenix/issues/2285).

**Comment by tim-krieger** [comment]
I copied favicon.ico to images and changed the following in /lib/mindwendel_web/templates/layout/kits_static_page.html.leex

`<link rel="icon" type="image/x-icon" href="<%= Routes.static_path(@conn, "/images/favicon.ico") %>">`

Now the favicon is shown on the landing page but not in the app :)

**Comment by JannikStreek** [comment]
the PR should work, please go ahead and test it :)

**Comment by tim-krieger** [comment]
Perfecto!

Maybe related: Shouldn't the filename be `apple-icon-180x180.png`?

`<link rel="apple-touch-icon" sizes="180x180" href="<%= Routes.static_path(@conn, "/images/kits_logo/apple-touch-icon-180x180.png") %>">`
