### ISSUE TITLE
Improve URL recognition

### ISSUE THREAD

**Issue by tim-krieger** [kitsteam/mindwendel#9]
https://kits.blog/ works
https://kits.blog doesn't work

**Comment by JannikStreek** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/606519/109700142-b578cf80-7b91-11eb-95fb-277740c3ded9.png)

works for me...or what am i doing wrong?

**Comment by tim-krieger** [comment]
This is strange. I thought I had tested it. But you're right. It works as expected.
